sudo: required
dist: trusty
branches:
  only:
    - master
    - dev
    - lva-37
notifications:
  email:
    on_success: always
    on_failure: always
  slack:
    rooms:
      - secure: c5WWnc0fqkQjUWd44/V0w2tBVP795zTYl6EuJlYcmzy4YhDOCXmxQmk51UjN4Eh/9GfFRdrMVH35pjY74AF4wG6agfw0Xy1lzT6WxsyU+STdKaC4p1p3qKnHH80jrokETcJ7QfVBU3sRW6f0auIWSakHd47v7+QcBpJKDDr1sCPgXQfXmbHHKfcPQqXnoUk5pD+EEcOQDGTM1OkskPJg8QYLwMEmSsCBNOE21AvV1mxw67HQTT4TteM8W4Wyffun1vk1rEq01NRr7cVC9ik79JX8YnxwWF29kRtfItoSFbc83MAoqO+fiOxKkvZRKXz0U+Offx/Ni7CP25oWcDVQ37tFafDXeAsi61TaNHt5rK5NXZkr6TidE4bBvEcsMQEz4FHYQrGliJWCe2fsuAgOhhzIhcSgQETbhc8g67TshqGS0agOhT9tTx8Yxmf3Y+g3hB6mkPKi8MpsoL7Dn++RXahimqUWuc37pylFrLU4Bi9lepNubWoh9mz0F1P98kfJp3Zk2DeK3vvWNp5UyA9M5uzpfQtS4VtY24w1rf4yaUTXBP0gbdIb1BJzKV6IutIZl2f2R7nM6WXHPfcVNlDcszSmAaeasfYUZ/XAoCprctSbGDqhMVyrfInvCLxtxEKBzl3teRJ3tC8mx51AE1BZf601EEX/yblgzq+xVUxzSoo=
    on_success: always
    on_failure: always
language: php
php:
  - 7.1
install:
  - nvm install v8.1.2
before_script:
  - phpenv config-rm xdebug.ini
  - cp env.travis .env
  - composer install --no-progress --no-suggest --no-interaction --optimize-autoloader
  - php artisan key:generate
  - npm install
  - npm rebuild node-sass
  - npm run production
  - touch database/database.sqlite
  - php artisan migrate

  - phantomjs --webdriver=127.0.0.1:9515 &
  - php artisan serve &
  - sleep 5

script:
  - vendor/bin/phpunit
  - php artisan dusk