branches:
  only:
    - master
    - dev
notifications:
  email:
    on_success: always
    on_failure: always
  slack:
    secure: Rw4A1EOomJpWvwtlfvJg2pOtTjspKY+KS7eNGC0GISnolax1DJ0MIHugRvWfQ3bIDECK/+/p3uxFeMYB/6gNJ6294mnr68XaVxgbqtk8OHi4fMBkAX0Csb+tUM6/Wg+DVKdaOll6Qhz8qaWJWlpGJHVFYojfaKy8cv/xqqnmNASJlsZVZvocVxJPlH3YZr/Tu9MDpTmUJcyIgXdpCGvBHTqIowpaA6QVsTVN5aZU+zJ1lz+w7LXMp2KbcFSFlT23IoJXV4uR78SmVFktxNl8NQYG4Aow1gV1Uwsb8aYIK2nXUZIiy16AtFWi+oGG2X4yxFW0yf0zhrmEcUMwHvwiE9bO1RWzF+nfFA3wpT+tQywJOHo/qjIgMpJVBO2emvXrn6oyS5lq3oWfwni7ye3Bxs8iM4rs6Bmvm6rXo04jHG+il+NDVk6L0Qi95OsVILNSaPoPt7vG2keImPuMbUJUC4+x3S38IY9WjdQtAb1bgl8/cgQ5Cw7T6DJzqcDIu0/8rvbdO8+/zcU41IN/8W3c7Ib+sMiCxsQLMzdo6pvx5cr2RtZq1tfjRxx5UXodeiAX6fXe9vHXSA67GggnM8f/5G23VPG4E2Ud0SN+pjj77o6qFaKu0zrEZl8WabMDDOiFy+6FkzZfjGtiKW8G7dex7Zyf0UiwtE4JZMsQNvgCe44=
    on_success: always
    on_failure: always
language: php
php:
  - 7.1
install:
  - nvm install v5.12.0
before_script:
  - phpenv config-rm xdebug.ini
  - npm install
  - composer install --no-interaction
  - export DISABLE_NOTIFIER=true; node_modules/gulp/bin/gulp.js
  - cp env.travis .env
  - php artisan key:generate
  - mysql -e 'create database lva_testing;'
script:
  - vendor/bin/phpunit