branches:
  only:
    - master
    - dev
notifications:
  email:
    on_success: always
    on_failure: always
language: php
php:
  - 7.1
install:
  - nvm install v5.12.0
before_script:
  - phpenv config-rm xdebug.ini
  - npm install
  - composer install --no-interaction
  - export DISABLE_NOTIFIER=true; node_modules/gulp/bin/gulp.js
  - cp env.travis .env
  - php artisan key:generate
  - mysql -e 'create database lva_testing;'
script:
  - vendor/bin/phpunit