language: php

php:
  - 7.3

addons:
  chrome: stable

branches:
  only:
  - master

install:
  - cp .env.ci .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - npm install
  - npm rebuild node-sass
  - npm run production

before_script:
  - phpenv config-rm xdebug.ini
  - touch database/database.sqlite
  - php artisan migrate
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - vendor/bin/phpunit
  - php artisan dusk

notifications:
  email:
    on_success: always
    on_failure: always
  slack:
    rooms:
      - secure: c5WWnc0fqkQjUWd44/V0w2tBVP795zTYl6EuJlYcmzy4YhDOCXmxQmk51UjN4Eh/9GfFRdrMVH35pjY74AF4wG6agfw0Xy1lzT6WxsyU+STdKaC4p1p3qKnHH80jrokETcJ7QfVBU3sRW6f0auIWSakHd47v7+QcBpJKDDr1sCPgXQfXmbHHKfcPQqXnoUk5pD+EEcOQDGTM1OkskPJg8QYLwMEmSsCBNOE21AvV1mxw67HQTT4TteM8W4Wyffun1vk1rEq01NRr7cVC9ik79JX8YnxwWF29kRtfItoSFbc83MAoqO+fiOxKkvZRKXz0U+Offx/Ni7CP25oWcDVQ37tFafDXeAsi61TaNHt5rK5NXZkr6TidE4bBvEcsMQEz4FHYQrGliJWCe2fsuAgOhhzIhcSgQETbhc8g67TshqGS0agOhT9tTx8Yxmf3Y+g3hB6mkPKi8MpsoL7Dn++RXahimqUWuc37pylFrLU4Bi9lepNubWoh9mz0F1P98kfJp3Zk2DeK3vvWNp5UyA9M5uzpfQtS4VtY24w1rf4yaUTXBP0gbdIb1BJzKV6IutIZl2f2R7nM6WXHPfcVNlDcszSmAaeasfYUZ/XAoCprctSbGDqhMVyrfInvCLxtxEKBzl3teRJ3tC8mx51AE1BZf601EEX/yblgzq+xVUxzSoo=
    on_success: always
    on_failure: always
