version: '3'

services:

  web:
    container_name: lva-web
    image: troccoli/laravel:7.3.4
    volumes:
      - ./:/var/www/vhosts/app:z
    ports:
      - 8081:80
    depends_on:
      - mysql
    environment:
      XDEBUG_CONFIG: "remote_host=172.17.0.1"
      PHP_IDE_CONFIG: "serverName=lva"

  mysql:
    container_name: lva-mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - 13306:3306
    volumes:
      - ./.docker/config/mysql/initdb.d:/docker-entrypoint-initdb.d:z
      - ./.docker/database:/var/lib/mysql:z

  mailhog:
    container_name: lva-mailhog
    image: mailhog/mailhog
    ports:
      - 18025:8025
      - 11025:1025

  selenium:
    container_name: lva-selenium
    image: selenium/standalone-chrome:3.141.59-oxygen
    environment:
      START_XVFB: "false"
    depends_on:
      - web
    volumes:
      - /dev/shm:/dev/shm
    links:
      - web:selenium.test

  cypress:
    container_name: lva-cypress
    image: cypress/included:4.1.0
    depends_on:
      - web
    environment:
      - CYPRESS_baseUrl=http://web
    working_dir: /e2e
    command: npx cypress run
    volumes:
      - ./tests/End2End/:/e2e
