version: '3'
services:
  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: app-web
    image: app-docker
    volumes:
      - ./:/var/www/vhosts/app:z
    ports:
      - 8080:80
    depends_on:
      - mysql
#    links:
#      - redis
    environment:
      XDEBUG_CONFIG: "remote_host=172.17.0.1"
      PHP_IDE_CONFIG: "serverName=app"
  mysql:
    container_name: app-mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - 13306:3306
    volumes:
      - ./.docker/config/mysql/initdb.d:/docker-entrypoint-initdb.d:z
      - ./.docker/database:/var/lib/mysql:z
#  redis:
#    image: redis:4.0-alpine
#    ports:
#      - 16379:6379
  mailhog:
    container_name: app-mailhog
    image: mailhog/mailhog
    ports:
      - 18025:8025
