version: 2
jobs:
  build:
    branches:
      only:
        - master
        - travis-for-laravel-5.8
    docker:
      - image: circleci/php:7.3-stretch-node-browsers

    steps:
      - checkout
      - run: sudo apt-get install -y libsqlite3-dev
      - run: cp .env.ci .env
      - run: composer install -n --ignore-platform-reqs
      - run: npm install
      - run: npm run production
      - run: touch database/database.sqlite
      - run: php artisan migrate
      - run: vendor/bin/phpunit

      - run:
          name: Start Chrome Driver
          command: ./vendor/laravel/dusk/bin/chromedriver-linux
          background: true

      - run:
          name: Run Laravel Server
          command: php artisan serve
          background: true

      - run:
          name: Run Laravel Dusk Tests
          command: php artisan dusk
