version: 2.1

orbs:
  cypress: cypress-io/cypress

jobs:
  build:
#    branches:
#      only:
#        - master

    docker:
      - image: circleci/php:7.3.4-stretch-node-browsers

    steps:
      - run:
          name: Install SQLite library
          command: sudo apt-get install -y libsqlite3-dev

      - checkout

      - run:
          name: Setup Environment
          command: |
            cp .env.ci .env
            touch ./storage/logs/laravel.log
            touch ./database/database.sqlite

      - restore_cache:
          keys:
            - composer-v2-{{ checksum "composer.lock" }}
            - composer-v2-
      - run:
          name: Install Composer Dependencies
          command: composer install -n --ignore-platform-reqs --no-progress --no-suggest
      - save_cache:
          key: composer-v2-{{ checksum "composer.lock" }}
          paths:
            - vendor

      - restore_cache:
          keys:
            - node-v2-{{ checksum "package-lock.json" }}
            - node-v2-
      - run:
          name: Install Node Dependencies
          command: |
            node --version
            npm --version
            npm install
      - save_cache:
          key: node-v2-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          name: Run Webpack
          command: npm run prod

      - run:
          name: Migrate Database
          command: php artisan migrate --force

      - run:
          name: Setup Laravel Passport
          command: php artisan passport:install

      - run:
          name: Run Unit Tests
          command: |
            mkdir -p ./logs/phpunit
            vendor/bin/phpunit -d memory_limit=512M --log-junit logs/phpunit/junit.xml --testdox-html logs/phpunit/testdox.html

      - run:
          name: Update Chrome Driver
          command: |
            CHROME_VERSION="$(google-chrome --version)"
            CHROMEDRIVER_RELEASE="$(echo $CHROME_VERSION | sed 's/^Google Chrome //')"
            CHROMEDRIVER_RELEASE=${CHROMEDRIVER_RELEASE%%.*}
            php artisan dusk:chrome-driver $CHROMEDRIVER_RELEASE

      - run:
          name: Start Chrome Driver
          command: ./vendor/laravel/dusk/bin/chromedriver-linux
          background: true

      - run:
          name: Run Laravel Server
          command: php artisan serve
          background: true

      - run:
          name: Run Laravel Dusk Tests
          command: php artisan dusk

      - store_artifacts:
          path: ./logs/phpunit
          destination: phpunit

      - store_artifacts:
          path: ./tests/Browser/console
          destination: console

      - store_artifacts:
          path: ./tests/Browser/screenshots
          destination: screenshots

      - store_artifacts:
          path: ./storage/logs
          destination: laravel

workflows:
  build:
    jobs:
      - cypress/run:
          store_artifacts: true
