<?php

Route::singularResourceParameters();

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@showHome')->name('home');
// The /home URL is hard-coded in the Auth code generated by Laravel artisan
// Rather than change the generated code, I defined its route
Route::any('/home', 'HomeController@showHome');

/* Authentication */
Route::auth();

/* Admin */
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {
    Route::get('data-management', 'DataManagementController@showHome')->name('data-management');
    Route::group(['prefix' => 'data-management', 'namespace' => 'DataManagement'], function () {
        Route::resource('seasons', 'SeasonsController');
        Route::resource('clubs', 'ClubsController');
        Route::resource('venues', 'VenuesController');
        Route::resource('roles', 'RolesController');
        Route::resource('divisions', 'DivisionsController');
        Route::resource('teams', 'TeamsController');
        Route::resource('fixtures', 'FixturesController');
        Route::resource('available-appointments', 'AvailableAppointmentsController');

        Route::group(['prefix' => 'upload'], function () {
            Route::get('fixtures', 'LoadController@uploadFixtures')->name('uploadFixtures');
            Route::post('fixtures', 'LoadController@startUploadFixtures')->name('uploadFixtures');
            Route::get('status/{uploadJob}', 'LoadController@uploadStatus')->name('uploadStatus');
        });
    });
});
