name: lva

on: [push, pull_request]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Print versions
        run: |
          composer --version
          node --version
          npm --version
      - name: Setup Environment
        run: |
          cp .env.ci .env
          touch ./storage/logs/laravel.log
          touch ./database/database.sqlite
      - name: Install Dependencies
        run: |
          composer install -n --ignore-platform-reqs --no-progress --no-suggest
          npm install
      - name: Run Webpack
        run: npm run prod
      - name: Migrate Database
        run: php artisan migrate --force
      - name: Setup Laravel Passport
        run: php artisan passport:install
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: |
#          mkdir -p ./logs/phpunit
          vendor/bin/phpunit
#          vendor/bin/phpunit -d memory_limit=512M --log-junit logs/phpunit/junit.xml --testdox-html logs/phpunit/testdox.html

